--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 17.2

-- Started on 2025-05-14 10:24:35

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 298 (class 1259 OID 29851)
-- Name: Ciclos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Ciclos" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    siglas character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text,
    id_ciclo uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public."Ciclos" OWNER TO postgres;

--
-- TOC entry 299 (class 1259 OID 29861)
-- Name: Cursos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cursos" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    centro character varying DEFAULT ''::character varying NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text,
    anyo character varying DEFAULT ''::character varying NOT NULL,
    id_curso uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public."Cursos" OWNER TO postgres;

--
-- TOC entry 300 (class 1259 OID 29872)
-- Name: Discentes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Discentes" (
    nombre text NOT NULL,
    apellidos text NOT NULL,
    correo text,
    fecha_nac date,
    localidad text,
    id_discente uuid DEFAULT gen_random_uuid() NOT NULL,
    imagen text,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public."Discentes" OWNER TO postgres;

--
-- TOC entry 301 (class 1259 OID 29877)
-- Name: Evaluaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Evaluaciones" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    fecha_ini date,
    fecha_fin date,
    descripcion text DEFAULT ''::text,
    id_tipoevaluacion bigint,
    id_evaluacion uuid DEFAULT gen_random_uuid() NOT NULL,
    id_curso uuid
);


ALTER TABLE public."Evaluaciones" OWNER TO postgres;

--
-- TOC entry 302 (class 1259 OID 29886)
-- Name: Modulos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Modulos" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    siglas character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text,
    id_modulo uuid DEFAULT gen_random_uuid() NOT NULL,
    id_ciclo uuid
);


ALTER TABLE public."Modulos" OWNER TO postgres;

--
-- TOC entry 303 (class 1259 OID 29896)
-- Name: Practicas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Practicas" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre text DEFAULT ''::text NOT NULL,
    numero character varying DEFAULT ''::character varying NOT NULL,
    enunciado text DEFAULT ''::text NOT NULL,
    descripcion text DEFAULT ''::text,
    id_tipopractica text NOT NULL,
    unidad character varying DEFAULT ''::character varying NOT NULL,
    id_practica uuid DEFAULT gen_random_uuid() NOT NULL,
    id_modulo uuid
);


ALTER TABLE public."Practicas" OWNER TO postgres;

--
-- TOC entry 304 (class 1259 OID 29908)
-- Name: TipoEvaluacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TipoEvaluacion" (
    id_tipoevaluacion bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text
);


ALTER TABLE public."TipoEvaluacion" OWNER TO postgres;

--
-- TOC entry 305 (class 1259 OID 29916)
-- Name: TipoEvaluacion_id_tipoevaluacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TipoEvaluacion" ALTER COLUMN id_tipoevaluacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TipoEvaluacion_id_tipoevaluacion_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 306 (class 1259 OID 29917)
-- Name: TipoPracticas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TipoPracticas" (
    id_tipopractica bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text
);


ALTER TABLE public."TipoPracticas" OWNER TO postgres;

--
-- TOC entry 307 (class 1259 OID 29925)
-- Name: TipoPracticas_id_tipopractica_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TipoPracticas" ALTER COLUMN id_tipopractica ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TipoPracticas_id_tipopractica_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 324 (class 1259 OID 62653)
-- Name: disponen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disponen (
    id_disponen uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    peso integer,
    id_practica uuid,
    id_evaluacion uuid
);


ALTER TABLE public.disponen OWNER TO postgres;

--
-- TOC entry 4009 (class 0 OID 0)
-- Dependencies: 324
-- Name: TABLE disponen; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.disponen IS 'PRACTICAS_EVALUACIONES';


--
-- TOC entry 308 (class 1259 OID 29936)
-- Name: evaluan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluan (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    peso smallint NOT NULL,
    id_evaluan uuid DEFAULT gen_random_uuid() NOT NULL,
    id_practica uuid NOT NULL,
    id_evaluacion uuid NOT NULL,
    id_discente uuid NOT NULL,
    nota integer NOT NULL
);


ALTER TABLE public.evaluan OWNER TO postgres;

--
-- TOC entry 309 (class 1259 OID 29943)
-- Name: hacen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hacen (
    id_hacen bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    curso character varying DEFAULT ''::character varying NOT NULL,
    nota smallint NOT NULL,
    id_practica bigint NOT NULL,
    id_discente bigint
);


ALTER TABLE public.hacen OWNER TO postgres;

--
-- TOC entry 310 (class 1259 OID 29950)
-- Name: hacen_id_hacen_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hacen ALTER COLUMN id_hacen ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hacen_id_hacen_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 311 (class 1259 OID 29951)
-- Name: imparte; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.imparte (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    notas character varying,
    id_imparte uuid DEFAULT gen_random_uuid() NOT NULL,
    id_curso uuid,
    id_modulo uuid,
    id_discente uuid
);


ALTER TABLE public.imparte OWNER TO postgres;

--
-- TOC entry 325 (class 1259 OID 65470)
-- Name: listado_evaluaciones; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.listado_evaluaciones WITH (security_invoker='on') AS
 SELECT evalua.id_discente,
    evalua.peso,
    evalua.nota,
    e.nombre AS nombre_evaluacion,
    e.id_evaluacion,
    e.fecha_ini,
    e.fecha_fin,
    d.nombre AS nombre_discente,
    d.apellidos,
    p.id_practica,
    p.numero,
    p.enunciado,
    p.unidad,
    p.nombre AS nombre_practica
   FROM public.evaluan evalua,
    public."Evaluaciones" e,
    public."Discentes" d,
    public."Practicas" p
  WHERE ((evalua.id_evaluacion = e.id_evaluacion) AND (evalua.id_discente = d.id_discente) AND (evalua.id_practica = p.id_practica));


ALTER VIEW public.listado_evaluaciones OWNER TO postgres;

--
-- TOC entry 327 (class 1259 OID 72530)
-- Name: listado_evaluaciones_ciclos; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.listado_evaluaciones_ciclos WITH (security_invoker='on') AS
 SELECT evalua.id_discente,
    evalua.peso,
    evalua.nota,
    e.nombre AS nombre_evaluacion,
    e.id_evaluacion,
    e.fecha_ini,
    e.fecha_fin,
    d.nombre AS nombre_discente,
    d.apellidos,
    p.id_practica,
    p.numero,
    p.enunciado,
    p.unidad,
    p.nombre AS nombre_practica,
    c.nombre AS nombre_curso,
    c.anyo,
    c.id_curso,
    c.descripcion,
    m.id_modulo,
    m.nombre AS nombre_modulo,
    m.siglas AS siglas_modulo,
    ci.id_ciclo,
    ci.nombre AS nombre_ciclo,
    ci.siglas AS siglas_ciclo
   FROM public.evaluan evalua,
    public."Evaluaciones" e,
    public."Discentes" d,
    public."Practicas" p,
    public."Cursos" c,
    public."Modulos" m,
    public."Ciclos" ci
  WHERE ((evalua.id_evaluacion = e.id_evaluacion) AND (evalua.id_discente = d.id_discente) AND (evalua.id_practica = p.id_practica) AND (e.id_curso = c.id_curso) AND (p.id_modulo = m.id_modulo) AND (m.id_ciclo = ci.id_ciclo));


ALTER VIEW public.listado_evaluaciones_ciclos OWNER TO postgres;

--
-- TOC entry 326 (class 1259 OID 70020)
-- Name: listado_evaluaciones_cursos; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.listado_evaluaciones_cursos WITH (security_invoker='on') AS
 SELECT evalua.id_discente,
    evalua.peso,
    evalua.nota,
    e.nombre AS nombre_evaluacion,
    e.id_evaluacion,
    e.fecha_ini,
    e.fecha_fin,
    d.nombre AS nombre_discente,
    d.apellidos,
    p.id_practica,
    p.numero,
    p.enunciado,
    p.unidad,
    p.nombre AS nombre_practica,
    c.nombre AS nombre_curso,
    c.anyo,
    c.id_curso,
    c.descripcion
   FROM public.evaluan evalua,
    public."Evaluaciones" e,
    public."Discentes" d,
    public."Practicas" p,
    public."Cursos" c
  WHERE ((evalua.id_evaluacion = e.id_evaluacion) AND (evalua.id_discente = d.id_discente) AND (evalua.id_practica = p.id_practica) AND (e.id_curso = c.id_curso));


ALTER VIEW public.listado_evaluaciones_cursos OWNER TO postgres;

--
-- TOC entry 312 (class 1259 OID 29959)
-- Name: matricula; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matricula (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    curso character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text,
    repetidor boolean,
    id_matricula uuid DEFAULT gen_random_uuid() NOT NULL,
    id_modulo uuid,
    id_discente uuid
);


ALTER TABLE public.matricula OWNER TO postgres;

--
-- TOC entry 313 (class 1259 OID 29968)
-- Name: poseen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.poseen (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    id_poseen uuid DEFAULT gen_random_uuid() NOT NULL,
    id_practica uuid,
    id_modulo uuid
);


ALTER TABLE public.poseen OWNER TO postgres;

--
-- TOC entry 3768 (class 2606 OID 62592)
-- Name: Ciclos Ciclos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ciclos"
    ADD CONSTRAINT "Ciclos_pkey" PRIMARY KEY (id_ciclo);


--
-- TOC entry 3770 (class 2606 OID 62561)
-- Name: Cursos Cursos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cursos"
    ADD CONSTRAINT "Cursos_pkey" PRIMARY KEY (id_curso);


--
-- TOC entry 3772 (class 2606 OID 62523)
-- Name: Discentes Discentes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Discentes"
    ADD CONSTRAINT "Discentes_pkey" PRIMARY KEY (id_discente);


--
-- TOC entry 3774 (class 2606 OID 62571)
-- Name: Evaluaciones Evaluaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Evaluaciones"
    ADD CONSTRAINT "Evaluaciones_pkey" PRIMARY KEY (id_evaluacion);


--
-- TOC entry 3776 (class 2606 OID 62580)
-- Name: Modulos Modulos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Modulos"
    ADD CONSTRAINT "Modulos_pkey" PRIMARY KEY (id_modulo);


--
-- TOC entry 3778 (class 2606 OID 62553)
-- Name: Practicas Practicas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Practicas"
    ADD CONSTRAINT "Practicas_pkey" PRIMARY KEY (id_practica);


--
-- TOC entry 3780 (class 2606 OID 30095)
-- Name: TipoEvaluacion TipoEvaluacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TipoEvaluacion"
    ADD CONSTRAINT "TipoEvaluacion_pkey" PRIMARY KEY (id_tipoevaluacion);


--
-- TOC entry 3782 (class 2606 OID 30097)
-- Name: TipoPracticas TipoPracticas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TipoPracticas"
    ADD CONSTRAINT "TipoPracticas_pkey" PRIMARY KEY (id_tipopractica);


--
-- TOC entry 3794 (class 2606 OID 62662)
-- Name: disponen disponen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disponen
    ADD CONSTRAINT disponen_pkey PRIMARY KEY (id_disponen);


--
-- TOC entry 3784 (class 2606 OID 62684)
-- Name: evaluan evaluan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluan
    ADD CONSTRAINT evaluan_pkey PRIMARY KEY (id_evaluan);


--
-- TOC entry 3786 (class 2606 OID 30103)
-- Name: hacen hacen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hacen
    ADD CONSTRAINT hacen_pkey PRIMARY KEY (id_hacen);


--
-- TOC entry 3788 (class 2606 OID 62642)
-- Name: imparte imparte_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imparte
    ADD CONSTRAINT imparte_pkey PRIMARY KEY (id_imparte);


--
-- TOC entry 3790 (class 2606 OID 62624)
-- Name: matricula matricula_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula
    ADD CONSTRAINT matricula_pkey PRIMARY KEY (id_matricula);


--
-- TOC entry 3792 (class 2606 OID 72570)
-- Name: poseen poseen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.poseen
    ADD CONSTRAINT poseen_pkey PRIMARY KEY (id_poseen);


--
-- TOC entry 3795 (class 2606 OID 30230)
-- Name: Evaluaciones Evaluacion_id_tipoevaluacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Evaluaciones"
    ADD CONSTRAINT "Evaluacion_id_tipoevaluacion_fkey" FOREIGN KEY (id_tipoevaluacion) REFERENCES public."TipoEvaluacion"(id_tipoevaluacion);


--
-- TOC entry 3796 (class 2606 OID 62610)
-- Name: Evaluaciones Evaluaciones_id_curso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Evaluaciones"
    ADD CONSTRAINT "Evaluaciones_id_curso_fkey" FOREIGN KEY (id_curso) REFERENCES public."Cursos"(id_curso) ON UPDATE CASCADE;


--
-- TOC entry 3797 (class 2606 OID 62593)
-- Name: Modulos Modulos_id_ciclo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Modulos"
    ADD CONSTRAINT "Modulos_id_ciclo_fkey" FOREIGN KEY (id_ciclo) REFERENCES public."Ciclos"(id_ciclo) ON UPDATE CASCADE;


--
-- TOC entry 3798 (class 2606 OID 62605)
-- Name: Practicas Practicas_id_modulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Practicas"
    ADD CONSTRAINT "Practicas_id_modulo_fkey" FOREIGN KEY (id_modulo) REFERENCES public."Modulos"(id_modulo) ON UPDATE CASCADE;


--
-- TOC entry 3807 (class 2606 OID 62663)
-- Name: disponen disponen_id_evaluacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disponen
    ADD CONSTRAINT disponen_id_evaluacion_fkey FOREIGN KEY (id_evaluacion) REFERENCES public."Evaluaciones"(id_evaluacion) ON UPDATE CASCADE;


--
-- TOC entry 3808 (class 2606 OID 62668)
-- Name: disponen disponen_id_practica_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disponen
    ADD CONSTRAINT disponen_id_practica_fkey FOREIGN KEY (id_practica) REFERENCES public."Practicas"(id_practica) ON UPDATE CASCADE;


--
-- TOC entry 3799 (class 2606 OID 62695)
-- Name: evaluan evaluan_id_discente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluan
    ADD CONSTRAINT evaluan_id_discente_fkey FOREIGN KEY (id_discente) REFERENCES public."Discentes"(id_discente) ON UPDATE CASCADE;


--
-- TOC entry 3800 (class 2606 OID 62690)
-- Name: evaluan evaluan_id_evaluacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluan
    ADD CONSTRAINT evaluan_id_evaluacion_fkey FOREIGN KEY (id_evaluacion) REFERENCES public."Evaluaciones"(id_evaluacion) ON UPDATE CASCADE;


--
-- TOC entry 3801 (class 2606 OID 62685)
-- Name: evaluan evaluan_id_practica_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluan
    ADD CONSTRAINT evaluan_id_practica_fkey FOREIGN KEY (id_practica) REFERENCES public."Practicas"(id_practica) ON UPDATE CASCADE;


--
-- TOC entry 3802 (class 2606 OID 62643)
-- Name: imparte imparte_id_curso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imparte
    ADD CONSTRAINT imparte_id_curso_fkey FOREIGN KEY (id_curso) REFERENCES public."Cursos"(id_curso) ON UPDATE CASCADE;


--
-- TOC entry 3803 (class 2606 OID 73678)
-- Name: imparte imparte_id_discente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imparte
    ADD CONSTRAINT imparte_id_discente_fkey FOREIGN KEY (id_discente) REFERENCES public."Discentes"(id_discente) ON UPDATE CASCADE;


--
-- TOC entry 3804 (class 2606 OID 62648)
-- Name: imparte imparte_id_modulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imparte
    ADD CONSTRAINT imparte_id_modulo_fkey FOREIGN KEY (id_modulo) REFERENCES public."Modulos"(id_modulo) ON UPDATE CASCADE;


--
-- TOC entry 3805 (class 2606 OID 62630)
-- Name: matricula matricula_id_discente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula
    ADD CONSTRAINT matricula_id_discente_fkey FOREIGN KEY (id_discente) REFERENCES public."Discentes"(id_discente) ON UPDATE CASCADE;


--
-- TOC entry 3806 (class 2606 OID 62625)
-- Name: matricula matricula_id_modulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula
    ADD CONSTRAINT matricula_id_modulo_fkey FOREIGN KEY (id_modulo) REFERENCES public."Modulos"(id_modulo) ON UPDATE CASCADE;


--
-- TOC entry 3975 (class 3256 OID 30315)
-- Name: Ciclos Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Ciclos" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3976 (class 3256 OID 30316)
-- Name: Cursos Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Cursos" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3977 (class 3256 OID 30317)
-- Name: Discentes Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Discentes" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3978 (class 3256 OID 30318)
-- Name: Evaluaciones Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Evaluaciones" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3979 (class 3256 OID 30319)
-- Name: Modulos Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Modulos" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3980 (class 3256 OID 30320)
-- Name: Practicas Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Practicas" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3981 (class 3256 OID 30321)
-- Name: TipoEvaluacion Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."TipoEvaluacion" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3982 (class 3256 OID 30322)
-- Name: TipoPracticas Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."TipoPracticas" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3983 (class 3256 OID 30324)
-- Name: evaluan Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.evaluan FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3984 (class 3256 OID 30325)
-- Name: hacen Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.hacen FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3985 (class 3256 OID 30326)
-- Name: imparte Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.imparte FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3986 (class 3256 OID 30327)
-- Name: matricula Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.matricula FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3987 (class 3256 OID 30328)
-- Name: poseen Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.poseen FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3988 (class 3256 OID 30329)
-- Name: Modulos Actualizar autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Actualizar autentificados" ON public."Modulos" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3989 (class 3256 OID 30330)
-- Name: Modulos Borrar para usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Borrar para usuarios autentificados" ON public."Modulos" FOR DELETE TO authenticated USING (true);


--
-- TOC entry 3961 (class 0 OID 29851)
-- Dependencies: 298
-- Name: Ciclos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Ciclos" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3962 (class 0 OID 29861)
-- Dependencies: 299
-- Name: Cursos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Cursos" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3963 (class 0 OID 29872)
-- Dependencies: 300
-- Name: Discentes; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Discentes" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3964 (class 0 OID 29877)
-- Dependencies: 301
-- Name: Evaluaciones; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Evaluaciones" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3990 (class 3256 OID 30331)
-- Name: Modulos Insertar; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Insertar" ON public."Modulos" FOR INSERT TO authenticated WITH CHECK (true);


--
-- TOC entry 3965 (class 0 OID 29886)
-- Dependencies: 302
-- Name: Modulos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Modulos" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3991 (class 3256 OID 30332)
-- Name: Ciclos Permisos totales; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Permisos totales" ON public."Ciclos" TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3992 (class 3256 OID 60256)
-- Name: Practicas Permisos totales; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Permisos totales" ON public."Practicas" TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3966 (class 0 OID 29896)
-- Dependencies: 303
-- Name: Practicas; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Practicas" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3967 (class 0 OID 29908)
-- Dependencies: 304
-- Name: TipoEvaluacion; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."TipoEvaluacion" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3968 (class 0 OID 29917)
-- Dependencies: 306
-- Name: TipoPracticas; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."TipoPracticas" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3974 (class 0 OID 62653)
-- Dependencies: 324
-- Name: disponen; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.disponen ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3969 (class 0 OID 29936)
-- Dependencies: 308
-- Name: evaluan; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluan ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3970 (class 0 OID 29943)
-- Dependencies: 309
-- Name: hacen; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.hacen ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3971 (class 0 OID 29951)
-- Dependencies: 311
-- Name: imparte; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.imparte ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3972 (class 0 OID 29959)
-- Dependencies: 312
-- Name: matricula; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.matricula ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3973 (class 0 OID 29968)
-- Dependencies: 313
-- Name: poseen; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.poseen ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3999 (class 0 OID 0)
-- Dependencies: 298
-- Name: TABLE "Ciclos"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Ciclos" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Ciclos" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Ciclos" TO service_role;


--
-- TOC entry 4000 (class 0 OID 0)
-- Dependencies: 299
-- Name: TABLE "Cursos"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Cursos" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Cursos" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Cursos" TO service_role;


--
-- TOC entry 4001 (class 0 OID 0)
-- Dependencies: 300
-- Name: TABLE "Discentes"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Discentes" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Discentes" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Discentes" TO service_role;


--
-- TOC entry 4002 (class 0 OID 0)
-- Dependencies: 301
-- Name: TABLE "Evaluaciones"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Evaluaciones" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Evaluaciones" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Evaluaciones" TO service_role;


--
-- TOC entry 4003 (class 0 OID 0)
-- Dependencies: 302
-- Name: TABLE "Modulos"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Modulos" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Modulos" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Modulos" TO service_role;


--
-- TOC entry 4004 (class 0 OID 0)
-- Dependencies: 303
-- Name: TABLE "Practicas"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Practicas" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Practicas" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Practicas" TO service_role;


--
-- TOC entry 4005 (class 0 OID 0)
-- Dependencies: 304
-- Name: TABLE "TipoEvaluacion"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoEvaluacion" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoEvaluacion" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoEvaluacion" TO service_role;


--
-- TOC entry 4006 (class 0 OID 0)
-- Dependencies: 305
-- Name: SEQUENCE "TipoEvaluacion_id_tipoevaluacion_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."TipoEvaluacion_id_tipoevaluacion_seq" TO anon;
GRANT ALL ON SEQUENCE public."TipoEvaluacion_id_tipoevaluacion_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."TipoEvaluacion_id_tipoevaluacion_seq" TO service_role;


--
-- TOC entry 4007 (class 0 OID 0)
-- Dependencies: 306
-- Name: TABLE "TipoPracticas"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoPracticas" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoPracticas" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoPracticas" TO service_role;


--
-- TOC entry 4008 (class 0 OID 0)
-- Dependencies: 307
-- Name: SEQUENCE "TipoPracticas_id_tipopractica_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."TipoPracticas_id_tipopractica_seq" TO anon;
GRANT ALL ON SEQUENCE public."TipoPracticas_id_tipopractica_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."TipoPracticas_id_tipopractica_seq" TO service_role;


--
-- TOC entry 4010 (class 0 OID 0)
-- Dependencies: 324
-- Name: TABLE disponen; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.disponen TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.disponen TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.disponen TO service_role;


--
-- TOC entry 4011 (class 0 OID 0)
-- Dependencies: 308
-- Name: TABLE evaluan; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.evaluan TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.evaluan TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.evaluan TO service_role;


--
-- TOC entry 4012 (class 0 OID 0)
-- Dependencies: 309
-- Name: TABLE hacen; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.hacen TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.hacen TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.hacen TO service_role;


--
-- TOC entry 4013 (class 0 OID 0)
-- Dependencies: 310
-- Name: SEQUENCE hacen_id_hacen_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.hacen_id_hacen_seq TO anon;
GRANT ALL ON SEQUENCE public.hacen_id_hacen_seq TO authenticated;
GRANT ALL ON SEQUENCE public.hacen_id_hacen_seq TO service_role;


--
-- TOC entry 4014 (class 0 OID 0)
-- Dependencies: 311
-- Name: TABLE imparte; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.imparte TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.imparte TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.imparte TO service_role;


--
-- TOC entry 4015 (class 0 OID 0)
-- Dependencies: 325
-- Name: TABLE listado_evaluaciones; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.listado_evaluaciones TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.listado_evaluaciones TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.listado_evaluaciones TO service_role;


--
-- TOC entry 4016 (class 0 OID 0)
-- Dependencies: 327
-- Name: TABLE listado_evaluaciones_ciclos; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.listado_evaluaciones_ciclos TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.listado_evaluaciones_ciclos TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.listado_evaluaciones_ciclos TO service_role;


--
-- TOC entry 4017 (class 0 OID 0)
-- Dependencies: 326
-- Name: TABLE listado_evaluaciones_cursos; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.listado_evaluaciones_cursos TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.listado_evaluaciones_cursos TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.listado_evaluaciones_cursos TO service_role;


--
-- TOC entry 4018 (class 0 OID 0)
-- Dependencies: 312
-- Name: TABLE matricula; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.matricula TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.matricula TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.matricula TO service_role;


--
-- TOC entry 4019 (class 0 OID 0)
-- Dependencies: 313
-- Name: TABLE poseen; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.poseen TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.poseen TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.poseen TO service_role;


-- Completed on 2025-05-14 10:24:40

--
-- PostgreSQL database dump complete
--

