--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 17.2

-- Started on 2025-05-04 10:56:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 20 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4009 (class 0 OID 0)
-- Dependencies: 20
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 272 (class 1259 OID 29851)
-- Name: Ciclos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Ciclos" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    siglas character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text,
    id_ciclo uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public."Ciclos" OWNER TO postgres;

--
-- TOC entry 273 (class 1259 OID 29861)
-- Name: Cursos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cursos" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    centro character varying DEFAULT ''::character varying NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text,
    anyo character varying DEFAULT ''::character varying NOT NULL,
    id_curso uuid DEFAULT gen_random_uuid() NOT NULL
);


ALTER TABLE public."Cursos" OWNER TO postgres;

--
-- TOC entry 274 (class 1259 OID 29872)
-- Name: Discentes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Discentes" (
    nombre text NOT NULL,
    apellidos text NOT NULL,
    correo text,
    fecha_nac date,
    localidad text,
    id_discente uuid DEFAULT gen_random_uuid() NOT NULL,
    imagen text
);


ALTER TABLE public."Discentes" OWNER TO postgres;

--
-- TOC entry 275 (class 1259 OID 29877)
-- Name: Evaluaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Evaluaciones" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    fecha_ini date,
    fecha_fin date,
    descripcion text DEFAULT ''::text,
    id_tipoevaluacion bigint,
    id_evaluacion uuid DEFAULT gen_random_uuid() NOT NULL,
    id_curso uuid
);


ALTER TABLE public."Evaluaciones" OWNER TO postgres;

--
-- TOC entry 276 (class 1259 OID 29886)
-- Name: Modulos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Modulos" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    siglas character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text,
    id_modulo uuid DEFAULT gen_random_uuid() NOT NULL,
    id_ciclo uuid
);


ALTER TABLE public."Modulos" OWNER TO postgres;

--
-- TOC entry 277 (class 1259 OID 29896)
-- Name: Practicas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Practicas" (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre text DEFAULT ''::text NOT NULL,
    numero character varying DEFAULT ''::character varying NOT NULL,
    enunciado text DEFAULT ''::text NOT NULL,
    descripcion text DEFAULT ''::text,
    id_tipopractica bigint NOT NULL,
    unidad character varying DEFAULT ''::character varying NOT NULL,
    id_practica uuid DEFAULT gen_random_uuid() NOT NULL,
    id_modulo uuid DEFAULT gen_random_uuid()
);


ALTER TABLE public."Practicas" OWNER TO postgres;

--
-- TOC entry 278 (class 1259 OID 29908)
-- Name: TipoEvaluacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TipoEvaluacion" (
    id_tipoevaluacion bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text
);


ALTER TABLE public."TipoEvaluacion" OWNER TO postgres;

--
-- TOC entry 279 (class 1259 OID 29916)
-- Name: TipoEvaluacion_id_tipoevaluacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TipoEvaluacion" ALTER COLUMN id_tipoevaluacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TipoEvaluacion_id_tipoevaluacion_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 29917)
-- Name: TipoPracticas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TipoPracticas" (
    id_tipopractica bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nombre character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text
);


ALTER TABLE public."TipoPracticas" OWNER TO postgres;

--
-- TOC entry 281 (class 1259 OID 29925)
-- Name: TipoPracticas_id_tipopractica_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TipoPracticas" ALTER COLUMN id_tipopractica ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TipoPracticas_id_tipopractica_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 282 (class 1259 OID 29926)
-- Name: Versiones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Versiones" (
    id_version bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    curso character varying DEFAULT ''::character varying,
    descripcion text DEFAULT ''::text,
    notas_version text DEFAULT ''::text,
    id_practica bigint NOT NULL
);


ALTER TABLE public."Versiones" OWNER TO postgres;

--
-- TOC entry 283 (class 1259 OID 29935)
-- Name: Versiones_id_version_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Versiones" ALTER COLUMN id_version ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Versiones_id_version_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 301 (class 1259 OID 62653)
-- Name: disponen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disponen (
    id_disponen uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    peso integer,
    id_practica uuid,
    id_evaluacion uuid
);


ALTER TABLE public.disponen OWNER TO postgres;

--
-- TOC entry 4023 (class 0 OID 0)
-- Dependencies: 301
-- Name: TABLE disponen; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.disponen IS 'PRACTICAS_EVALUACIONES';


--
-- TOC entry 284 (class 1259 OID 29936)
-- Name: evaluan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluan (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    peso smallint NOT NULL,
    id_evaluan uuid DEFAULT gen_random_uuid() NOT NULL,
    id_practica uuid,
    id_evaluacion uuid,
    id_discente uuid,
    nota integer
);


ALTER TABLE public.evaluan OWNER TO postgres;

--
-- TOC entry 285 (class 1259 OID 29943)
-- Name: hacen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hacen (
    id_hacen bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    curso character varying DEFAULT ''::character varying NOT NULL,
    nota smallint NOT NULL,
    id_practica bigint NOT NULL,
    id_discente bigint
);


ALTER TABLE public.hacen OWNER TO postgres;

--
-- TOC entry 286 (class 1259 OID 29950)
-- Name: hacen_id_hacen_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hacen ALTER COLUMN id_hacen ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hacen_id_hacen_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 287 (class 1259 OID 29951)
-- Name: imparte; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.imparte (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    curso character varying DEFAULT ''::character varying,
    descripcion character varying,
    id_imparte uuid DEFAULT gen_random_uuid() NOT NULL,
    id_curso uuid,
    id_modulo uuid
);


ALTER TABLE public.imparte OWNER TO postgres;

--
-- TOC entry 288 (class 1259 OID 29959)
-- Name: matricula; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matricula (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    curso character varying DEFAULT ''::character varying NOT NULL,
    descripcion text DEFAULT ''::text,
    repetidor boolean,
    id_matricula uuid DEFAULT gen_random_uuid() NOT NULL,
    id_modulo uuid,
    id_discente uuid
);


ALTER TABLE public.matricula OWNER TO postgres;

--
-- TOC entry 289 (class 1259 OID 29968)
-- Name: poseen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.poseen (
    id_poseen bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    curso character varying DEFAULT ''::character varying NOT NULL,
    id_modulo bigint NOT NULL,
    id_proactica bigint NOT NULL
);


ALTER TABLE public.poseen OWNER TO postgres;

--
-- TOC entry 290 (class 1259 OID 29975)
-- Name: poseen_id_poseen_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.poseen ALTER COLUMN id_poseen ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.poseen_id_poseen_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3984 (class 0 OID 29851)
-- Dependencies: 272
-- Data for Name: Ciclos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Ciclos" (created_at, nombre, siglas, descripcion, id_ciclo) FROM stdin;
2025-03-11 11:55:24.763055+00	Administración de Sistemas Informáticos en Red	ASIR	El término Administración de Sistemas Informáticos en Red hace referencia a una profesión que implica gestionar, mantener y asegurar el correcto funcionamiento de los sistemas informáticos en una red. Además es el nombre que adquiere el Grado Superior de Formación Profesional (FP) donde los alumnos se convierten en técnicos profesionales. Es importante porque garantiza la disponibilidad, seguridad y eficiencia de los recursos tecnológicos, facilitando el flujo de información y el funcionamiento de las organizaciones.	3eb505e1-d0d0-46eb-87bb-d4cbb7ff7833
2025-03-11 11:55:24.763055+00	Desarrollo de Aplicaciones Web	DAW	El Grado Superior en Desarrollo de Aplicaciones Web es un título oficial de Formación Profesional perteneciente a la rama de Informática. La titulación, también conocida como DAW, está acreditada por el Ministerio de Educación.En esta FP conocerás la parte front end de la programación así como aspectos fundamentales de la parte back o ámbitos transversales como los sistemas informáticos o las bases de datos. 	36cabd1e-c173-495d-94fc-51bfe6df800d
2025-03-11 11:55:24.763055+00	Desarrollo de Aplicaciones Multiplataforma	DAM	DAM es una titulación oficial de grado superior que se encuentra dentro de la rama de FP Informática. Como Técnico Superior en Desarrollo de Aplicaciones Multiplataforma de Desarrollo de Aplicaciones Multiplataforma aprenderás todo lo que necesitas saber sobre sistemas informáticos, bases de datos y programación front y back end, adquiriendo así un aprendizaje más completo.	5f032c9e-08f1-41de-bc4c-19a3ac2827fe
2025-03-11 11:55:24.763055+00	Desarrollo de VideoJuegos y Realidad Virtual	CEVRV	La competencia general de este curso de especialización consiste en diseñar y desarrollar videojuegos para diferentes dispositivos y plataformas, garantizando la experiencia del usuario, utilizando herramientas de última generación que permitan actuar en todas las fases de su desarrollo, así como aplicaciones interactivas de realidad virtual y aumentada.	a906f924-b287-4acf-a170-f743152c2aa3
2025-03-11 11:55:24.763055+00	Sistemas Microinformáticos y Redes	SMR	Sistemas Microinformáticos y Redes es una profesión que se centra en el diseño, implementación y mantenimiento de sistemas informáticos a pequeña escala, incluyendo redes de computadoras y la administración de hardware, software y servicios relacionados para garantizar su funcionamiento eficiente y seguro. La labor del Técnico SMR es importante porque gracias a ella se asegura la eficiencia y seguridad de los sistemas informáticos en empresas e instituciones.	56951ab9-cc40-421b-84ce-730b167edbfe
\.


--
-- TOC entry 3985 (class 0 OID 29861)
-- Dependencies: 273
-- Data for Name: Cursos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Cursos" (created_at, centro, nombre, descripcion, anyo, id_curso) FROM stdin;
2024-12-23 16:53:50.698609+00	IES Tecnológico	1º DAW	Primer curso de Desarrollo de Aplicaciones Web	2024-2025	15726b48-92d4-4741-9b10-70f5181416ce
2024-12-23 16:53:50.698609+00	IES Tecnológico	2º DAW	Segundo curso de Desarrollo de Aplicaciones Web	2024-2025	c400ed1d-2566-45a6-bfbc-40661fb7f0e8
2024-12-23 16:53:50.698609+00	IES Tecnológico	1º ASI	Primer curso de Administración de Sistemas Informáticos	2024-2025	615b047d-5bc4-44e5-97d5-6a4f395212b6
\.


--
-- TOC entry 3986 (class 0 OID 29872)
-- Dependencies: 274
-- Data for Name: Discentes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Discentes" (nombre, apellidos, correo, fecha_nac, localidad, id_discente, imagen) FROM stdin;
María	López García	mlopez@example.com	2002-06-15	Petrer	c168177d-04c3-4fcb-8d62-9239391e9933	\N
Juan	Pérez Martínez	jperez@example.com	2003-02-20	Petrer	2284f4c8-c81d-4e9a-adec-53a08cd5c307	\N
Ana	González Ruiz	agonzalez@example.com	2001-12-10	Novelda	187d730d-9fa3-40db-bdd0-e2bc5848effd	\N
Carlos	Fernández Soto	cfernandez@example.com	2002-03-05	Aspe	61459399-ff3e-4c65-ac3f-990a02378022	\N
Laura	Ramírez Torres	lramirez@example.com	2003-07-22	Elda	bed3e57a-9aff-4025-8177-aeb842762706	\N
\.


--
-- TOC entry 3987 (class 0 OID 29877)
-- Dependencies: 275
-- Data for Name: Evaluaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Evaluaciones" (created_at, nombre, fecha_ini, fecha_fin, descripcion, id_tipoevaluacion, id_evaluacion, id_curso) FROM stdin;
2024-12-23 16:57:35.875658+00	Primera Evaluación	2024-10-01	2024-12-20	Evaluación inicial	1	60aac5f9-be85-4247-9ba5-7d507a316a17	\N
2024-12-23 16:57:35.875658+00	Segunda Evaluación	2025-01-15	2025-03-30	Evaluación intermedia	2	b4d1a473-948e-4e54-8467-5db73c296d7d	\N
2024-12-23 16:57:35.875658+00	Evaluación Final	2025-04-01	2025-06-20	Evaluación final	3	024a3941-68fd-4037-8ec3-45be8ba27a4a	\N
\.


--
-- TOC entry 3988 (class 0 OID 29886)
-- Dependencies: 276
-- Data for Name: Modulos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Modulos" (created_at, nombre, siglas, descripcion, id_modulo, id_ciclo) FROM stdin;
2025-03-11 12:24:31.301724+00	Montaje y mantenimiento de equipos	MME	En este módulo se aprende a ensamblar y mantener equipos informáticos, identificando y solucionando posibles fallos de hardware.	3e0d4355-eca3-4fc4-954b-6342b6a99c9d	56951ab9-cc40-421b-84ce-730b167edbfe
2025-03-11 12:24:31.301724+00	Sistemas operativos monopuesto	SOM	Se centra en la instalación, configuración y administración de sistemas operativos en equipos individuales, asegurando su correcto funcionamiento.	02617676-b7aa-4b2d-b913-f902097183a7	56951ab9-cc40-421b-84ce-730b167edbfe
2025-03-11 12:24:31.301724+00	Sistemas operativos en red	SOR	Este módulo aborda la instalación y gestión de sistemas operativos diseñados para funcionar en entornos de red, facilitando la comunicación y el intercambio de recursos entre equipos.	0fff16bd-b8bb-4746-b574-29eda9e04d45	56951ab9-cc40-421b-84ce-730b167edbfe
2025-03-11 12:24:31.301724+00	Aplicaciones ofimáticas	AOF	Se adquieren habilidades en el uso de herramientas ofimáticas, como procesadores de texto, hojas de cálculo y software de presentaciones, esenciales para el entorno empresarial.	451f9f42-25b8-42b5-a2f1-a70fe92563ef	56951ab9-cc40-421b-84ce-730b167edbfe
2025-03-11 12:24:31.301724+00	Administración de sistemas operativos	ASO	Se profundiza en la gestión avanzada de sistemas operativos, incluyendo la administración de servicios, la optimización del rendimiento y la implementación de políticas de seguridad para proteger la integridad del sistema.	ebc4d0ed-1bfc-4427-bd04-3d8620063220	3eb505e1-d0d0-46eb-87bb-d4cbb7ff7833
2025-03-11 12:24:31.301724+00	Fundamentos de hardware	FHW	Este módulo proporciona conocimientos sobre los componentes físicos de los sistemas informáticos, enseñando a identificar, montar y mantener hardware, así como a diagnosticar y solucionar problemas relacionados.	ab9e5c22-8a0f-421a-82ba-2d0d4fa6fbeb	3eb505e1-d0d0-46eb-87bb-d4cbb7ff7833
2025-03-11 12:24:31.301724+00	Desarrollo de Interfaces	DIN	Se aprende a diseñar y programar interfaces de usuario intuitivas y funcionales, considerando aspectos de usabilidad y experiencia del usuario (UX).	38039f93-d31d-4e2e-a213-dd3113f282ae	5f032c9e-08f1-41de-bc4c-19a3ac2827fe
2025-03-11 12:24:31.301724+00	Implantación de sistemas operativos	ISO	Este módulo se centra en la instalación, configuración y administración de sistemas operativos, tanto en entornos monopuesto como en red. Los estudiantes aprenden a gestionar recursos, usuarios y permisos, asegurando el correcto funcionamiento del sistema.	81ac77a1-5ec1-4462-ab3c-f11887ad37c1	3eb505e1-d0d0-46eb-87bb-d4cbb7ff7833
2025-03-11 12:24:31.301724+00	Diseño de Interfaces Web	DIW	Se trabajan principios de usabilidad, accesibilidad, experiencia de usuario (UX/UI) y diseño responsivo con CSS y frameworks como Bootstrap o Tailwind CSS. Se estudian herramientas de diseño como Figma.	2122f6ea-9294-4e24-87cd-b2e8dbc14e1a	36cabd1e-c173-495d-94fc-51bfe6df800d
2025-03-11 12:24:31.301724+00	Desarrollo Web en Entorno Cliente	DWC	Se aprende a desarrollar la parte visual y dinámica de las aplicaciones web utilizando HTML, CSS y JavaScript. Se profundiza en frameworks y librerías como React, Vue.js o Angular, así como en la manipulación del DOM y AJAX para mejorar la experiencia del usuario.	0cacc34d-36b1-435b-b51d-318d9c55d21c	36cabd1e-c173-495d-94fc-51bfe6df800d
2025-03-11 12:24:31.301724+00	Sistemas informáticos (DAW)	SIW	Se aprende a instalar, configurar y administrar sistemas operativos en entornos de servidor y cliente. Se abordan conceptos de hardware, redes, gestión de usuarios y permisos, virtualización y seguridad informática.	d6cde104-7477-4ec4-a2d5-488a779fbfeb	36cabd1e-c173-495d-94fc-51bfe6df800d
2025-03-11 12:24:31.301724+00	Sistemas de Gestión Empresarial	SGE	Una introducción al desarrollo y adaptación de soluciones informáticas para la gestión empresarial, incluyendo sistemas ERP y CRM, que optimizan procesos internos de las organizaciones.	7e9898d4-5623-4e4c-99bb-f0d64b2ddf0f	5f032c9e-08f1-41de-bc4c-19a3ac2827fe
2025-03-11 12:24:31.301724+00	Programación de Servicios y Procesos	PSP	Se estudian técnicas para desarrollar servicios y procesos en segundo plano que permitan a las aplicaciones realizar tareas de manera eficiente, garantizando una adecuada gestión de recursos.	6eda6257-1c5b-4e77-8c8c-64dbeabdba4b	5f032c9e-08f1-41de-bc4c-19a3ac2827fe
2025-03-11 12:24:31.301724+00	Sistemas informáticos (DAM)	SIM	Se aprende a instalar, configurar y administrar sistemas operativos en entornos de servidor y cliente. Se abordan conceptos de hardware, redes, gestión de usuarios y permisos, virtualización y seguridad informática.	13b0ec2f-2c41-4574-baf5-44c113856983	5f032c9e-08f1-41de-bc4c-19a3ac2827fe
2025-03-11 12:24:31.301724+00	Programación y motores de videojuegos	PMV	Se centra en el uso de lenguajes de programación y motores gráficos para el desarrollo de videojuegos. Los estudiantes aprenden a implementar funcionalidades, físicas y lógica de juego, optimizando el rendimiento en diferentes plataformas.	4b93ccc8-e684-4b4f-95d7-6c147c12ff56	a906f924-b287-4acf-a170-f743152c2aa3
2025-03-11 12:24:31.301724+00	Diseño, gestión, publicación y producción	DGP	Este módulo aborda las fases de creación de un videojuego, desde la conceptualización de la idea hasta su implementación. Se estudian aspectos como mecánicas de juego, narrativa, diseño de niveles y experiencia del usuario.	a4a00b5e-c0f4-4361-80dd-76cd7d071f5b	a906f924-b287-4acf-a170-f743152c2aa3
2025-03-11 12:24:31.301724+00	Diseño gráfico 2D y 3D	D23	Se enfoca en la creación de modelos tridimensionales y su animación para su uso en videojuegos y aplicaciones de realidad virtual. Los estudiantes aprenden técnicas de modelado, texturizado y rigging.	a453dc0e-5a1f-4a88-b6dd-7a0f666ab763	a906f924-b287-4acf-a170-f743152c2aa3
2025-03-11 12:24:31.301724+00	Realidad virtual y realidad aumentada	RVA	Este módulo introduce a las tecnologías de realidad virtual (VR) y realidad aumentada (AR), enseñando a desarrollar aplicaciones inmersivas que integren elementos virtuales en entornos reales o completamente digitales.	9959ed1a-40b6-48ee-9e19-770ae926853d	a906f924-b287-4acf-a170-f743152c2aa3
2025-03-11 12:24:31.301724+00	Programación en red e inteligencia artificial	PRI	Está diseñado para que los estudiantes adquieran competencias en el desarrollo de aplicaciones que operan en entornos de red y que incorporan técnicas de inteligencia artificial (IA)	786bbf7d-619f-4715-b423-fde00bbe47dd	a906f924-b287-4acf-a170-f743152c2aa3
\.


--
-- TOC entry 3989 (class 0 OID 29896)
-- Dependencies: 277
-- Data for Name: Practicas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Practicas" (created_at, nombre, numero, enunciado, descripcion, id_tipopractica, unidad, id_practica, id_modulo) FROM stdin;
2024-12-23 16:55:03.734992+00	Práctica 2	P2	Diseño de una base de datos	Práctica intermedia	2	Unidad 2	34aa470d-9603-4c20-9630-18552f737374	\N
2024-12-23 16:55:52.895551+00	Práctica 2	P2	Diseño de una base de datos	Práctica intermedia	2	Unidad 2	4f9fce57-1519-4a3b-a41b-9a8b03aaa350	\N
2024-12-23 16:55:52.895551+00	Práctica 1	P1	Resolver ejercicios básicos de programación	Práctica introductoria	1	Unidad 1	78cda6f1-29dd-439e-9581-6252226dd457	\N
2024-12-23 16:55:03.734992+00	Práctica 4	P4	Desarrollar una página web interactiva chula	Práctica avanzada	3	Unidad 3	8c05faff-cff6-40ae-a6a9-d0f97fb3168b	\N
2024-12-23 16:55:03.734992+00	Práctica 1	P133	Resolver ejercicios básicos de programación	Práctica introductoria	1	Unidad 1	bef77cbb-4232-474b-8b8a-fa4b5ec980d1	\N
2024-12-23 16:55:52.895551+00	Práctica 3	P3	Desarrollar una página web interactiva	Práctica avanzada	3	Unidad 3	dab273c3-5f11-4df7-9098-5eec77503741	\N
\.


--
-- TOC entry 3990 (class 0 OID 29908)
-- Dependencies: 278
-- Data for Name: TipoEvaluacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TipoEvaluacion" (id_tipoevaluacion, created_at, nombre, descripcion) FROM stdin;
1	2024-12-23 16:57:35.875658+00	Parcial	Evaluación parcial de contenidos
2	2024-12-23 16:57:35.875658+00	Global	Evaluación global del módulo
3	2024-12-23 16:57:35.875658+00	Extraordinaria	Evaluación para recuperación
4	2025-02-13 15:41:43.932251+00	Final	Evaluación final del módulo
\.


--
-- TOC entry 3992 (class 0 OID 29917)
-- Dependencies: 280
-- Data for Name: TipoPracticas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TipoPracticas" (id_tipopractica, created_at, nombre, descripcion) FROM stdin;
1	2024-12-23 16:50:56.799831+00	Individual	Práctica realizada de forma individual
2	2024-12-23 16:50:56.799831+00	Grupal	Práctica realizada en equipo
3	2024-12-23 16:50:56.799831+00	Proyecto	Proyecto complejo integrador
4	2024-12-23 16:58:25.454745+00	Individual	Práctica realizada de forma individual
5	2024-12-23 16:58:25.454745+00	Grupal	Práctica realizada en equipo
6	2024-12-23 16:58:25.454745+00	Proyecto	Proyecto complejo integrador
\.


--
-- TOC entry 3994 (class 0 OID 29926)
-- Dependencies: 282
-- Data for Name: Versiones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Versiones" (id_version, created_at, curso, descripcion, notas_version, id_practica) FROM stdin;
7	2024-12-23 16:56:50.536362+00	2024-2025	Versión inicial	Primera iteración de la práctica	7
8	2024-12-23 16:56:50.536362+00	2024-2025	Versión revisada	Actualización basada en feedback	7
9	2024-12-23 16:56:50.536362+00	2024-2025	Versión inicial	Primera iteración de la práctica	8
10	2024-12-23 16:56:50.536362+00	2024-2025	Versión revisada	Actualización basada en feedback	8
11	2024-12-23 16:56:50.536362+00	2024-2025	Versión inicial	Primera iteración de la práctica	9
12	2024-12-23 16:56:50.536362+00	2024-2025	Versión revisada	Actualización basada en feedback	9
\.


--
-- TOC entry 4003 (class 0 OID 62653)
-- Dependencies: 301
-- Data for Name: disponen; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.disponen (id_disponen, created_at, peso, id_practica, id_evaluacion) FROM stdin;
\.


--
-- TOC entry 3996 (class 0 OID 29936)
-- Dependencies: 284
-- Data for Name: evaluan; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evaluan (created_at, peso, id_evaluan, id_practica, id_evaluacion, id_discente, nota) FROM stdin;
\.


--
-- TOC entry 3997 (class 0 OID 29943)
-- Dependencies: 285
-- Data for Name: hacen; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.hacen (id_hacen, created_at, curso, nota, id_practica, id_discente) FROM stdin;
\.


--
-- TOC entry 3999 (class 0 OID 29951)
-- Dependencies: 287
-- Data for Name: imparte; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.imparte (created_at, curso, descripcion, id_imparte, id_curso, id_modulo) FROM stdin;
\.


--
-- TOC entry 4000 (class 0 OID 29959)
-- Dependencies: 288
-- Data for Name: matricula; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.matricula (created_at, curso, descripcion, repetidor, id_matricula, id_modulo, id_discente) FROM stdin;
\.


--
-- TOC entry 4001 (class 0 OID 29968)
-- Dependencies: 289
-- Data for Name: poseen; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.poseen (id_poseen, created_at, curso, id_modulo, id_proactica) FROM stdin;
\.


--
-- TOC entry 4032 (class 0 OID 0)
-- Dependencies: 279
-- Name: TipoEvaluacion_id_tipoevaluacion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TipoEvaluacion_id_tipoevaluacion_seq"', 4, true);


--
-- TOC entry 4033 (class 0 OID 0)
-- Dependencies: 281
-- Name: TipoPracticas_id_tipopractica_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TipoPracticas_id_tipopractica_seq"', 6, true);


--
-- TOC entry 4034 (class 0 OID 0)
-- Dependencies: 283
-- Name: Versiones_id_version_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Versiones_id_version_seq"', 12, true);


--
-- TOC entry 4035 (class 0 OID 0)
-- Dependencies: 286
-- Name: hacen_id_hacen_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hacen_id_hacen_seq', 1, false);


--
-- TOC entry 4036 (class 0 OID 0)
-- Dependencies: 290
-- Name: poseen_id_poseen_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.poseen_id_poseen_seq', 1, false);


--
-- TOC entry 3758 (class 2606 OID 62592)
-- Name: Ciclos Ciclos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ciclos"
    ADD CONSTRAINT "Ciclos_pkey" PRIMARY KEY (id_ciclo);


--
-- TOC entry 3760 (class 2606 OID 62561)
-- Name: Cursos Cursos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cursos"
    ADD CONSTRAINT "Cursos_pkey" PRIMARY KEY (id_curso);


--
-- TOC entry 3762 (class 2606 OID 62523)
-- Name: Discentes Discentes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Discentes"
    ADD CONSTRAINT "Discentes_pkey" PRIMARY KEY (id_discente);


--
-- TOC entry 3764 (class 2606 OID 62571)
-- Name: Evaluaciones Evaluaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Evaluaciones"
    ADD CONSTRAINT "Evaluaciones_pkey" PRIMARY KEY (id_evaluacion);


--
-- TOC entry 3766 (class 2606 OID 62580)
-- Name: Modulos Modulos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Modulos"
    ADD CONSTRAINT "Modulos_pkey" PRIMARY KEY (id_modulo);


--
-- TOC entry 3768 (class 2606 OID 62553)
-- Name: Practicas Practicas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Practicas"
    ADD CONSTRAINT "Practicas_pkey" PRIMARY KEY (id_practica);


--
-- TOC entry 3770 (class 2606 OID 30095)
-- Name: TipoEvaluacion TipoEvaluacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TipoEvaluacion"
    ADD CONSTRAINT "TipoEvaluacion_pkey" PRIMARY KEY (id_tipoevaluacion);


--
-- TOC entry 3772 (class 2606 OID 30097)
-- Name: TipoPracticas TipoPracticas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TipoPracticas"
    ADD CONSTRAINT "TipoPracticas_pkey" PRIMARY KEY (id_tipopractica);


--
-- TOC entry 3774 (class 2606 OID 30099)
-- Name: Versiones Versiones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Versiones"
    ADD CONSTRAINT "Versiones_pkey" PRIMARY KEY (id_version);


--
-- TOC entry 3786 (class 2606 OID 62662)
-- Name: disponen disponen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disponen
    ADD CONSTRAINT disponen_pkey PRIMARY KEY (id_disponen);


--
-- TOC entry 3776 (class 2606 OID 62684)
-- Name: evaluan evaluan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluan
    ADD CONSTRAINT evaluan_pkey PRIMARY KEY (id_evaluan);


--
-- TOC entry 3778 (class 2606 OID 30103)
-- Name: hacen hacen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hacen
    ADD CONSTRAINT hacen_pkey PRIMARY KEY (id_hacen);


--
-- TOC entry 3780 (class 2606 OID 62642)
-- Name: imparte imparte_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imparte
    ADD CONSTRAINT imparte_pkey PRIMARY KEY (id_imparte);


--
-- TOC entry 3782 (class 2606 OID 62624)
-- Name: matricula matricula_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula
    ADD CONSTRAINT matricula_pkey PRIMARY KEY (id_matricula);


--
-- TOC entry 3784 (class 2606 OID 30109)
-- Name: poseen poseen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.poseen
    ADD CONSTRAINT poseen_pkey PRIMARY KEY (id_poseen);


--
-- TOC entry 3787 (class 2606 OID 30230)
-- Name: Evaluaciones Evaluacion_id_tipoevaluacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Evaluaciones"
    ADD CONSTRAINT "Evaluacion_id_tipoevaluacion_fkey" FOREIGN KEY (id_tipoevaluacion) REFERENCES public."TipoEvaluacion"(id_tipoevaluacion);


--
-- TOC entry 3788 (class 2606 OID 62610)
-- Name: Evaluaciones Evaluaciones_id_curso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Evaluaciones"
    ADD CONSTRAINT "Evaluaciones_id_curso_fkey" FOREIGN KEY (id_curso) REFERENCES public."Cursos"(id_curso) ON UPDATE CASCADE;


--
-- TOC entry 3789 (class 2606 OID 62593)
-- Name: Modulos Modulos_id_ciclo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Modulos"
    ADD CONSTRAINT "Modulos_id_ciclo_fkey" FOREIGN KEY (id_ciclo) REFERENCES public."Ciclos"(id_ciclo) ON UPDATE CASCADE;


--
-- TOC entry 3790 (class 2606 OID 62605)
-- Name: Practicas Practicas_id_modulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Practicas"
    ADD CONSTRAINT "Practicas_id_modulo_fkey" FOREIGN KEY (id_modulo) REFERENCES public."Modulos"(id_modulo) ON UPDATE CASCADE;


--
-- TOC entry 3798 (class 2606 OID 62663)
-- Name: disponen disponen_id_evaluacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disponen
    ADD CONSTRAINT disponen_id_evaluacion_fkey FOREIGN KEY (id_evaluacion) REFERENCES public."Evaluaciones"(id_evaluacion) ON UPDATE CASCADE;


--
-- TOC entry 3799 (class 2606 OID 62668)
-- Name: disponen disponen_id_practica_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disponen
    ADD CONSTRAINT disponen_id_practica_fkey FOREIGN KEY (id_practica) REFERENCES public."Practicas"(id_practica) ON UPDATE CASCADE;


--
-- TOC entry 3791 (class 2606 OID 62695)
-- Name: evaluan evaluan_id_discente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluan
    ADD CONSTRAINT evaluan_id_discente_fkey FOREIGN KEY (id_discente) REFERENCES public."Discentes"(id_discente) ON UPDATE CASCADE;


--
-- TOC entry 3792 (class 2606 OID 62690)
-- Name: evaluan evaluan_id_evaluacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluan
    ADD CONSTRAINT evaluan_id_evaluacion_fkey FOREIGN KEY (id_evaluacion) REFERENCES public."Evaluaciones"(id_evaluacion) ON UPDATE CASCADE;


--
-- TOC entry 3793 (class 2606 OID 62685)
-- Name: evaluan evaluan_id_practica_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluan
    ADD CONSTRAINT evaluan_id_practica_fkey FOREIGN KEY (id_practica) REFERENCES public."Practicas"(id_practica) ON UPDATE CASCADE;


--
-- TOC entry 3794 (class 2606 OID 62643)
-- Name: imparte imparte_id_curso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imparte
    ADD CONSTRAINT imparte_id_curso_fkey FOREIGN KEY (id_curso) REFERENCES public."Cursos"(id_curso) ON UPDATE CASCADE;


--
-- TOC entry 3795 (class 2606 OID 62648)
-- Name: imparte imparte_id_modulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imparte
    ADD CONSTRAINT imparte_id_modulo_fkey FOREIGN KEY (id_modulo) REFERENCES public."Modulos"(id_modulo) ON UPDATE CASCADE;


--
-- TOC entry 3796 (class 2606 OID 62630)
-- Name: matricula matricula_id_discente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula
    ADD CONSTRAINT matricula_id_discente_fkey FOREIGN KEY (id_discente) REFERENCES public."Discentes"(id_discente) ON UPDATE CASCADE;


--
-- TOC entry 3797 (class 2606 OID 62625)
-- Name: matricula matricula_id_modulo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matricula
    ADD CONSTRAINT matricula_id_modulo_fkey FOREIGN KEY (id_modulo) REFERENCES public."Modulos"(id_modulo) ON UPDATE CASCADE;


--
-- TOC entry 3964 (class 3256 OID 30315)
-- Name: Ciclos Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Ciclos" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3965 (class 3256 OID 30316)
-- Name: Cursos Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Cursos" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3966 (class 3256 OID 30317)
-- Name: Discentes Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Discentes" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3967 (class 3256 OID 30318)
-- Name: Evaluaciones Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Evaluaciones" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3968 (class 3256 OID 30319)
-- Name: Modulos Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Modulos" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3969 (class 3256 OID 30320)
-- Name: Practicas Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Practicas" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3970 (class 3256 OID 30321)
-- Name: TipoEvaluacion Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."TipoEvaluacion" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3971 (class 3256 OID 30322)
-- Name: TipoPracticas Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."TipoPracticas" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3972 (class 3256 OID 30323)
-- Name: Versiones Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public."Versiones" FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3973 (class 3256 OID 30324)
-- Name: evaluan Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.evaluan FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3974 (class 3256 OID 30325)
-- Name: hacen Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.hacen FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3975 (class 3256 OID 30326)
-- Name: imparte Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.imparte FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3976 (class 3256 OID 30327)
-- Name: matricula Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.matricula FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3977 (class 3256 OID 30328)
-- Name: poseen Acceso SELECT usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Acceso SELECT usuarios autentificados" ON public.poseen FOR SELECT TO authenticated USING (true);


--
-- TOC entry 3978 (class 3256 OID 30329)
-- Name: Modulos Actualizar autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Actualizar autentificados" ON public."Modulos" FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3979 (class 3256 OID 30330)
-- Name: Modulos Borrar para usuarios autentificados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Borrar para usuarios autentificados" ON public."Modulos" FOR DELETE TO authenticated USING (true);


--
-- TOC entry 3949 (class 0 OID 29851)
-- Dependencies: 272
-- Name: Ciclos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Ciclos" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3950 (class 0 OID 29861)
-- Dependencies: 273
-- Name: Cursos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Cursos" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3951 (class 0 OID 29872)
-- Dependencies: 274
-- Name: Discentes; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Discentes" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3952 (class 0 OID 29877)
-- Dependencies: 275
-- Name: Evaluaciones; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Evaluaciones" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3980 (class 3256 OID 30331)
-- Name: Modulos Insertar; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Insertar" ON public."Modulos" FOR INSERT TO authenticated WITH CHECK (true);


--
-- TOC entry 3953 (class 0 OID 29886)
-- Dependencies: 276
-- Name: Modulos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Modulos" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3981 (class 3256 OID 30332)
-- Name: Ciclos Permisos totales; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Permisos totales" ON public."Ciclos" TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3982 (class 3256 OID 60256)
-- Name: Practicas Permisos totales; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Permisos totales" ON public."Practicas" TO authenticated USING (true) WITH CHECK (true);


--
-- TOC entry 3954 (class 0 OID 29896)
-- Dependencies: 277
-- Name: Practicas; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Practicas" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3955 (class 0 OID 29908)
-- Dependencies: 278
-- Name: TipoEvaluacion; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."TipoEvaluacion" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3956 (class 0 OID 29917)
-- Dependencies: 280
-- Name: TipoPracticas; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."TipoPracticas" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3957 (class 0 OID 29926)
-- Dependencies: 282
-- Name: Versiones; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public."Versiones" ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3963 (class 0 OID 62653)
-- Dependencies: 301
-- Name: disponen; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.disponen ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3958 (class 0 OID 29936)
-- Dependencies: 284
-- Name: evaluan; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluan ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3959 (class 0 OID 29943)
-- Dependencies: 285
-- Name: hacen; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.hacen ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3960 (class 0 OID 29951)
-- Dependencies: 287
-- Name: imparte; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.imparte ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3961 (class 0 OID 29959)
-- Dependencies: 288
-- Name: matricula; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.matricula ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 3962 (class 0 OID 29968)
-- Dependencies: 289
-- Name: poseen; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.poseen ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 4010 (class 0 OID 0)
-- Dependencies: 20
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- TOC entry 4011 (class 0 OID 0)
-- Dependencies: 272
-- Name: TABLE "Ciclos"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Ciclos" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Ciclos" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Ciclos" TO service_role;


--
-- TOC entry 4012 (class 0 OID 0)
-- Dependencies: 273
-- Name: TABLE "Cursos"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Cursos" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Cursos" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Cursos" TO service_role;


--
-- TOC entry 4013 (class 0 OID 0)
-- Dependencies: 274
-- Name: TABLE "Discentes"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Discentes" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Discentes" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Discentes" TO service_role;


--
-- TOC entry 4014 (class 0 OID 0)
-- Dependencies: 275
-- Name: TABLE "Evaluaciones"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Evaluaciones" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Evaluaciones" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Evaluaciones" TO service_role;


--
-- TOC entry 4015 (class 0 OID 0)
-- Dependencies: 276
-- Name: TABLE "Modulos"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Modulos" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Modulos" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Modulos" TO service_role;


--
-- TOC entry 4016 (class 0 OID 0)
-- Dependencies: 277
-- Name: TABLE "Practicas"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Practicas" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Practicas" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Practicas" TO service_role;


--
-- TOC entry 4017 (class 0 OID 0)
-- Dependencies: 278
-- Name: TABLE "TipoEvaluacion"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoEvaluacion" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoEvaluacion" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoEvaluacion" TO service_role;


--
-- TOC entry 4018 (class 0 OID 0)
-- Dependencies: 279
-- Name: SEQUENCE "TipoEvaluacion_id_tipoevaluacion_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."TipoEvaluacion_id_tipoevaluacion_seq" TO anon;
GRANT ALL ON SEQUENCE public."TipoEvaluacion_id_tipoevaluacion_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."TipoEvaluacion_id_tipoevaluacion_seq" TO service_role;


--
-- TOC entry 4019 (class 0 OID 0)
-- Dependencies: 280
-- Name: TABLE "TipoPracticas"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoPracticas" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoPracticas" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."TipoPracticas" TO service_role;


--
-- TOC entry 4020 (class 0 OID 0)
-- Dependencies: 281
-- Name: SEQUENCE "TipoPracticas_id_tipopractica_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."TipoPracticas_id_tipopractica_seq" TO anon;
GRANT ALL ON SEQUENCE public."TipoPracticas_id_tipopractica_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."TipoPracticas_id_tipopractica_seq" TO service_role;


--
-- TOC entry 4021 (class 0 OID 0)
-- Dependencies: 282
-- Name: TABLE "Versiones"; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Versiones" TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Versiones" TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public."Versiones" TO service_role;


--
-- TOC entry 4022 (class 0 OID 0)
-- Dependencies: 283
-- Name: SEQUENCE "Versiones_id_version_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Versiones_id_version_seq" TO anon;
GRANT ALL ON SEQUENCE public."Versiones_id_version_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."Versiones_id_version_seq" TO service_role;


--
-- TOC entry 4024 (class 0 OID 0)
-- Dependencies: 301
-- Name: TABLE disponen; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.disponen TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.disponen TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.disponen TO service_role;


--
-- TOC entry 4025 (class 0 OID 0)
-- Dependencies: 284
-- Name: TABLE evaluan; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.evaluan TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.evaluan TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.evaluan TO service_role;


--
-- TOC entry 4026 (class 0 OID 0)
-- Dependencies: 285
-- Name: TABLE hacen; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.hacen TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.hacen TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.hacen TO service_role;


--
-- TOC entry 4027 (class 0 OID 0)
-- Dependencies: 286
-- Name: SEQUENCE hacen_id_hacen_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.hacen_id_hacen_seq TO anon;
GRANT ALL ON SEQUENCE public.hacen_id_hacen_seq TO authenticated;
GRANT ALL ON SEQUENCE public.hacen_id_hacen_seq TO service_role;


--
-- TOC entry 4028 (class 0 OID 0)
-- Dependencies: 287
-- Name: TABLE imparte; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.imparte TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.imparte TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.imparte TO service_role;


--
-- TOC entry 4029 (class 0 OID 0)
-- Dependencies: 288
-- Name: TABLE matricula; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.matricula TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.matricula TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.matricula TO service_role;


--
-- TOC entry 4030 (class 0 OID 0)
-- Dependencies: 289
-- Name: TABLE poseen; Type: ACL; Schema: public; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.poseen TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.poseen TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE public.poseen TO service_role;


--
-- TOC entry 4031 (class 0 OID 0)
-- Dependencies: 290
-- Name: SEQUENCE poseen_id_poseen_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.poseen_id_poseen_seq TO anon;
GRANT ALL ON SEQUENCE public.poseen_id_poseen_seq TO authenticated;
GRANT ALL ON SEQUENCE public.poseen_id_poseen_seq TO service_role;


--
-- TOC entry 2515 (class 826 OID 30352)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2518 (class 826 OID 30353)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2520 (class 826 OID 30354)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2521 (class 826 OID 30355)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2522 (class 826 OID 30356)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


--
-- TOC entry 2524 (class 826 OID 30357)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


-- Completed on 2025-05-04 10:56:10

--
-- PostgreSQL database dump complete
--

