name: Despliegue en servifor FTP

on:
  push:
    branches:
      - master

jobs:
  deploy-master:
    name: "master branch"
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Deploy"
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host: ${{ secrets.SERVER }}
          ftp_username: ${{ secrets.USER }}
          ftp_password: ${{ secrets.PASSWORD }}
          local_source_dir: "dist"
          dist_target_dir: "/"
          delete: "true"
          exclude: "'^logs/' '^README.md'"
